### ISSUE TITLE
How to encrypt a file?

### ISSUE THREAD

**Issue by keitaroemotion** [ueno/ruby-gpgme#100]
From README, I see only the way how to encrypt a plaintext.
What do I have to do to encrypt a file itself as argument?

**Comment by ueno** [comment]
Can't you simply pass a ```File``` object? If you are using the ```GPGME::Crypto``` API, it should be wrapped internally into a ```GPGME::Data``` object.

**Comment by keitaroemotion** [comment]
Could you show me the example on this?
I implemented encrypt_sign function as follows:

```
```
      def encrypt_sign(
        plaintext,
        recipient_pubkey,
        sender_privkey,
        binary: nil,
        password: nil
      )
        in_a_directory(binary) do
          options = pinentry_mode(password)
                      
          GPGME::Ctx.new(options) do |ctx|
            import(sender_privkey)  
            import(recipient_pubkey)

            ctx.add_signer(*(find(sender_privkey, :secret)))
            ctx.encrypt_sign(
              find(recipient_pubkey, :public),
              data(plaintext),
              data,
              GPGME::ENCRYPT_ALWAYS_TRUST
            ).to_s
          end
        end
      end

      private

      def binary(binary_file = nil)
        binary_file ||= ENV["PATH"]
          .split(/:/)
          .map    { |path| File.join(path, "gpg1") }
          .select { |path| File.exist?(path)       }
          .first
        validate_gpg_binary binary_file
        binary_file
      end

```

**Comment by keitaroemotion** [comment]
Could you show me the example on this?
I implemented encrypt_sign function as follows:

```
      def encrypt_sign(
        plaintext,
        recipient_pubkey,
        sender_privkey,
        binary: nil,
        password: nil
      )
        in_a_directory(binary) do
          options = pinentry_mode(password)
                      
          GPGME::Ctx.new(options) do |ctx|
            import(sender_privkey)  
            import(recipient_pubkey)

            ctx.add_signer(*(find(sender_privkey, :secret)))
            ctx.encrypt_sign(
              find(recipient_pubkey, :public),
              data(plaintext),
              data,
              GPGME::ENCRYPT_ALWAYS_TRUST
            ).to_s
          end
        end
      end
```

**Comment by keitaroemotion** [comment]
okay, thx

**Comment by ueno** [comment]
I meant something like:
```ruby
#!/usr/bin/env ruby
require 'gpgme'

plain = 'test test test'
puts("Plaintext:\n#{plain}")

crypto = GPGME::Crypto.new(:armor => true)
File.open('plain.txt') do |file|
  cipher = crypto.encrypt(file, {:symmetric => true})
  str = cipher.read
  puts("Ciphertext:\n#{str}")

  cipher = GPGME::Data.new(str)
  plain = crypto.decrypt(cipher)
  puts("Plaintext:\n#{plain.read}")
end
```
This actually works on my system.
