### ISSUE TITLE
Release version 2.0.14?

### ISSUE THREAD

**Issue by ivobenedito** [ueno/ruby-gpgme#103]
Hi @ueno 

Is it possible to release a new version of the gem containing the fix from master that solves the issue for installing this gem on ubuntu? Thx!

**Comment by ueno** [comment]
@dansketcher is this something you like to start with, perhaps?

**Comment by dansketcher** [comment]
Bumped and released, although rubygems.org doesn't like me yet.

**Comment by dansketcher** [comment]
@ueno I'll need you to add me to the gpgme project on rubygems per my email address, or alternatively you can push the release if you prefer :)

**Comment by ueno** [comment]
@dansketcher thanks, added your email

**Comment by dansketcher** [comment]
Bumped and pushed :)

**Comment by ivobenedito** [comment]
Thx @ueno @dansketcher 👍
