### ISSUE TITLE
Nokogiri 1.8.1 Compatibility

### ISSUE THREAD

**Issue by rcclemente** [ueno/ruby-gpgme#107]
Hi,

I work for company that uses ruby-gpgme for some of our projects. 
Currently nokogiri 1.6.8 has a vulnerability and we are in the process of updating gems and gpgme is not compatible with nokogiri 1.8.1

```
gpgme (~> 2.0) was resolved to 2.0.14, which depends on
        mini_portile2 (~> 2.1)

nokogiri (= 1.8.1) was resolved to 1.8.1, which depends on
      mini_portile2 (~> 2.3.0)
```

I would be willing to work on this if I am added as a contributor and help with updates in the future

Regards,
Ryan

**Comment by ueno** [comment]
Thank you, I have sent the request.
(I was not ignoring #106, but hesitating to merge it because of the existing CI failure.  I hope someone could fix it.)

**Comment by rcclemente** [comment]
@ueno Thanks
