### ISSUE TITLE
Streaming Example

### ISSUE THREAD

**Issue by joshuamcginnis** [ueno/ruby-gpgme#110]
I'm working on a worker which decrypts 20 * 5GB GPG encrypted files which each expand to about 12GB each. Due to ephemeral space limitations in our environment, I'd like to stream each file from S3, decrypt the file stream and then write the decrypted stream back to S3 using [multipart upload](https://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/S3Object.html#multipart_upload-instance_method).

Is this possible? Can I pass a stream to ruby-gpgme and redirect the decrypted stream? Are there any examples? Thanks!

**Comment by joshuamcginnis** [comment]
I've made some progress with this.

```ruby
output = File.open('out.txt', 'w+b')

s3_client.get_object(bucket: bucket, key: object_key) do |chunk|
  crypto.decrypt(chunk, password: password, output: output)
end
```

This streams and decrypt the first chunk to disk but then raises:
> gpgme-2.0.14/lib/gpgme/ctx.rb:435:in `decrypt_verify': Decryption failed (GPGME::Error::DecryptFailed)

Getting closer.

**Comment by joshuamcginnis** [comment]
I'm now able to stream a file directly from S3 to GPG and to disk without having to download the full file. The only issue is that the read size is 512 bytes and that will cause a lot of network latency if I'm only able to download the file in S3 512 bytes at a time?

@ueno @dansketcher Do either of you know how to set the read size?

```ruby
class CustomIO < StringIO
  def initialize
    s3_credentials = Aws::Credentials.new(AWS_ACCESS_KEY_ID, AWS_SECRET_KEY_ID)
    @s3_client = Aws::S3::Client.new(credentials: s3_credentials, region: 'us-east-1')
    @last_byte_read = 0
    super
  end

  def read(length)
    bucket = 'avant-acxiom'
    source_file = 'XREF_20160223.gpg'
    object_key = "upload/#{source_file}"

    result = @s3_client.get_object({
      bucket: bucket,
      key: object_key,
      range: "bytes=#{@last_byte_read}-#{@last_byte_read + length}"
    }).body.read(length)

    @last_byte_read += length
    result
  end
end

destination = File.open('out.txt', 'w+b')
example = GPGME::Data.new(CustomIO) 
crypto.decrypt(example, password: password, output: destination)
```

**Comment by ueno** [comment]
You are already using ```IOCallbacks``` through ```Data.new```, as it automatically wraps IO argument with ```IOCallbacks```.  By the way, why do you want GPG here instead of TLS in the first place?

**Comment by joshuamcginnis** [comment]
The source of confusion for me was how the `hook` param was invoked in an `IOCallbacks` instance.

I see now that [`GPGME::Data.from_callbacks`](http://www.rubydoc.info/github/ueno/ruby-gpgme/GPGME/Data#from_callbacks-class_method) accepts an optional `hook` param which would be passed to the `IOCallbacks` instance passed into the first argument.

And when the `Data` instance is created from callbacks, it passes the callbacks and hook value to `GPGME::gpgme_data_new_from_cbs` which calls out the GPG lib.

> Function: gpgme_error_t gpgme_data_new_from_cbs (gpgme_data_t *dh, gpgme_data_cbs_t cbs, void *handle)
The function gpgme_data_new_from_cbs creates a new gpgme_data_t object and uses the user-provided callback functions to operate on the data object.

With the key part being:
> The handle handle is passed as first argument to the callback functions. This can be used to identify this data object.

`hook` == `handle` and this is passed as the first arg to each method in the `IOCallback` instance passed in during the Data obj creation.
