### ISSUE TITLE
Update libgpg-error to fix build with gawk 5

### ISSUE THREAD

**Issue by Keruspe** [ueno/ruby-gpgme#134]
Build is currently broken with gawk 5 because the version of libgpg-error which is bundled cannot be built with it. Downgrading to gawk 4.x "fixes" the problem.
The issue is fixed upstream in https://github.com/gpg/libgpg-error/commit/7865041c77f4f7005282f10f9b6666b19072fbdf
Updating libgpg-error to the latest release should be enough to fix this.

**Comment by mashedkeyboard** [comment]
Just encountered this problem while trying to upgrade an application from Ruby 2.5.3 to 2.5.7. Can this be merged in as a priority? cc @dansketcher :)

**Comment by mashedkeyboard** [comment]
Update: having just tested this in https://github.com/mashedkeyboard/ruby-gpgme/tree/patch-1, the latest release is too old to fix this. A new libgpg-error release needs to be produced.

**Comment by mrohnstock** [comment]
@mashedkeyboard apply the following upstream patch and it should work:

https://github.com/gpg/libgpg-error/commit/7865041c77f4f7005282f10f9b6666b19072fbdf

**Comment by samgranieri** [comment]
I would also like a new release of this gem. Right now I have to install gnupg, libgpg-error, and libassuan from homebrew and install this gem using system libraries.

**Comment by Honiix** [comment]
There is a libgpg-error 1.37 beeing prepared: https://dev.gnupg.org/T4772

**Comment by dansketcher** [comment]
Good stuff thanks all for staying on this, your support is appreciated ❤️

**Comment by dansketcher** [comment]
Ok version is out, branch lib_version_upgrades_202002 tracks the change
https://github.com/ueno/ruby-gpgme/compare/lib_version_upgrades_202002
Please test!

**Comment by HarlemSquirrel** [comment]
Working well for me so far on Arch Linux with Ruby 2.7.0

**Comment by dansketcher** [comment]
@samgranieri @Keruspe @mashedkeyboard could you also check out the `lib_version_upgrades_202002` branch and let me know how you go?
Thanks :)

**Comment by Keruspe** [comment]
@dansketcher `Activating libgpg-error 1.37 (from /tmp/ruby-gpgme/ports/x86_64-pc-linux-gnu/libgpg-error/1.37)...` => Works ike a charm, thanks

**Comment by dansketcher** [comment]
No (bad) news then....

**Comment by dansketcher** [comment]
https://rubygems.org/gems/gpgme/versions/2.0.20
