### ISSUE TITLE
The mini_portile2 required version blocks updating if 2.8.0 is installed

### ISSUE THREAD

**Issue by schinery** [ueno/ruby-gpgme#164]
The required version of `mini_portile2` set as `"~> 2.7.0"` is too restrictive as it only allows `2.7.*` to be installed, and the current version of the `mini_portile2` is `2.8.0`, which would have been allowed by the previous setting `"~> 2.3"`. 

Because of this I'm unable to install the latest version of this gem with the Ubuntu stack fixes as my project has `2.8.0` of the `mini_portile2` already installed, at least without manually downgrading the `mini_portile2` gem in the `Gemfile.lock`.

I've had a go at loosing the required version [here](https://github.com/ueno/ruby-gpgme/pull/163).

**Comment by ueno** [comment]
I suppose we can close this, now that #163 has been merged.
