### ISSUE TITLE
the config.guess in libassuan-2.5.5.tar.bz2 is too old,and it cannot guess build type

### ISSUE THREAD

**Issue by zangruochen** [ueno/ruby-gpgme#173]
Architecture: loongarch64
LoongArch is a new architecture that is already supported by linux-6.1, gcc-12.
My build type is loongarch64-unknown-linux-gnu,and the config.guess in libassuan-2.5.5.tar.bz2 is too old,it cannot guess build type.
libassuan has released version 2.5.6 on 2023/06/19. The build type can be guessed using version 2.5.6.
https://www.gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.6.tar.bz2

**Comment by ueno** [comment]
A PR like this https://github.com/ueno/ruby-gpgme/commit/17e963648cf99055dcedad6086b997bd140828fa would be appreciated.

**Comment by zangruochen** [comment]
@ueno Hello,Thank you for your reply,I have submitted a pull request. #174

**Comment by ueno** [comment]
#174 merged now. Thank you.
