### ISSUE TITLE
Why does GPGME::VERSION not match Gemspec version?

### ISSUE THREAD

**Issue by mexisme** [ueno/ruby-gpgme#60]
I notice that `GPGME::VERSION` in https://github.com/ueno/ruby-gpgme/blob/master/lib/gpgme/version.rb does not match `s.version` in https://github.com/ueno/ruby-gpgme/blob/master/gpgme.gemspec

Is there a reason for this?
If so, it would be nice to have a short explanatory comment in `gpgme/version.rb`

**Comment by ueno** [comment]
no, it was a leftover. fixed in ab9d1e1e9531bfe0f09cc4ab0c8c02dbe2277c9c.
thanks for reporting that.
