### ISSUE TITLE
The bundled libgpg-error is incompatible with GCC 5

### ISSUE THREAD

**Issue by ignisf** [ueno/ruby-gpgme#65]
Hello,

Ran into this on my Arch system: https://gist.githubusercontent.com/ignisf/bc65828bace8460f501c/raw/f623893a173757f7853036cf3b1f9ee9a2e4c355/gistfile1.txt

Managed to install it with `--use-system-libraries`.

I believe that this has been fixed in later versions of libgpg-error

**Comment by ueno** [comment]
thanks, updated as d60493e97e4a32e92593f5047aca3f9cec588bbb.
will upload a new gem soon.

**Comment by ignisf** [comment]
Fixed in https://github.com/ueno/ruby-gpgme/releases/tag/2.0.9
Thank you
