### ISSUE TITLE
Using node GPG on client side

### ISSUE THREAD

**Issue by mujy** [ueno/ruby-gpgme#72]
Hello im new to javascript and was trying to use the GPG encryption/decryption functions, I was able to use npm to install and use libraries that do not have dependencies in themselves but GPG does. Would you mind showing me a way i can "require" GPG in a javascript file im using for a browser extension on the client side please? 
thank you in advance
-Mujy

**Comment by ueno** [comment]
I'm afraid you are looking at the wrong project (we are ruby-gpgme, not node gpg).
